# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X402 < Formula
  desc "CLI for testing x402-enabled payment-gated APIs"
  homepage "https://github.com/port402/x402-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_darwin_amd64.tar.gz"
      sha256 "76767d94674197fc5a37c2de6384c89403a240f5e44fdd3182bd75f7e3f7c9d9"

      def install
        bin.install "x402"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_darwin_arm64.tar.gz"
      sha256 "641acc518b73e3649d3974cd2315ca7bf31e8c9f406057a1c337424a1deb548e"

      def install
        bin.install "x402"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_linux_amd64.tar.gz"
      sha256 "10e6dbeb781869748a9d008952f6e78ad68b6e3ec59eb2f8dfa5e6360a4bcd3f"
      def install
        bin.install "x402"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_linux_arm64.tar.gz"
      sha256 "70b530eb572295ea00a38e723310ba8a3631fb12a07d0ac3dee2031675e01d5b"
      def install
        bin.install "x402"
      end
    end
  end

  test do
    system "#{bin}/x402", "version"
  end
end
