# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X402Cli < Formula
  desc "CLI for testing x402-enabled payment-gated APIs"
  homepage "https://github.com/port402/x402-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "f77c135a64763784c1e6c79a6b61c2c476f45cb92656e38f8933a7c2f20ecbb6"

      def install
        bin.install "x402"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "e2e53eee44acd2da9f2aed17e72f1cbec5e624008710260903f60960fa72c368"

      def install
        bin.install "x402"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "af588df2e2b4e922a229857bf6be2e56bcd99f82337423cc2ceee45597f6ebfd"
      def install
        bin.install "x402"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "d5af477a34baaf0e18b2b647951629dfcf48b8bcd68f75aadd5638719499884d"
      def install
        bin.install "x402"
      end
    end
  end

  test do
    system "#{bin}/x402", "version"
  end
end
