# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class X402Cli < Formula
  desc "CLI for testing x402-enabled payment-gated APIs"
  homepage "https://github.com/port402/x402-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_darwin_amd64.tar.gz"
      sha256 "e39cbfced3308d3331bcdbf765c96d3002a154fb31ddaf07184751d713405ab4"

      def install
        bin.install "x402"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_darwin_arm64.tar.gz"
      sha256 "db257beca8e9798c583a552d8b20da1d97fcc9e3f010bf6639e6c2823b49f560"

      def install
        bin.install "x402"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_linux_amd64.tar.gz"
      sha256 "27f3d07d76ea3d2f0279cd49e5893360f67038474da151c4e6392ef3815d386d"
      def install
        bin.install "x402"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/port402/x402-cli/releases/download/v0.1.0/x402_0.1.0_linux_arm64.tar.gz"
      sha256 "e4c9922bc78846cf61be3002a4c88f6b70281a94dad847796f0efd8e07a3c545"
      def install
        bin.install "x402"
      end
    end
  end

  test do
    system "#{bin}/x402", "version"
  end
end
